# Generated by Django 6.0.3 on 2026-03-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0002_alter_tipousuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='api_projeto.prestador'),
        ),
    ]
