# Generated by Django 6.0.3 on 2026-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0003_alter_servico_prestador'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
